services:
  postgres:
    image: postgres:15
    container_name: postgres-task-manager
    environment:
      POSTGRES_USER: ${POSTGRE_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRE_PASSWORD}
      POSTGRES_DB: task-manager
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data"
    restart: "no"

volumes:
  postgres_data: